#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="GIT"

export ZOPEN_GIT_URL="https://github.com/vim/vim.git"
export ZOPEN_GIT_DEPS="git make"
export ZOPEN_EXTRA_CONFIGURE_OPTS="--with-features=big --without-x --enable-gui=no --with-tlib=curses"
