#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
if ! [ -f buildenv ]; then
  echo "Need to source from the buildenv directory" >&2
  return 0
fi

export ZOPEN_ROOT="${PWD}"
export ZOPEN_TYPE="GIT"

export ZOPEN_GIT_URL="https://github.com/vim/vim.git"
export ZOPEN_GIT_DEPS="git make zoslib ncurses"
export ZOPEN_EXTRA_CONFIGURE_OPTS="--with-features=big --without-x --enable-gui=no"
export ZOPEN_CHECK="skip"

zopen_append_to_env() {
cat <<EOF
export VIM="\${PWD}/share/vim"
EOF
}
